import CreateRequest from './createrequest'; 
import Merchant from './merchant'; 
import ShopperInfo from './shopperinfo'; 
import CardTokenInput from './cardtokeninput'; 
import Token from './token'; 
import SepaBankAccount from './sepabankaccount'; 
import Country from './country'; 
import ListPaymentMethodsSuccess from './listpaymentmethodssuccess'; 
import Success from './success'; 
import ListPaymentMethodsErrors from './listpaymentmethodserrors'; 
import Error from './error'; 
import StatusSuccess from './statussuccess'; 
import StatusReport from './statusreport'; 
import ApproximateTotals from './approximatetotals'; 
import Payment from './payment'; 
import Authorization from './authorization'; 
import Amount from './amount'; 
import Capture from './capture'; 
import Refund from './refund'; 
import Chargeback from './chargeback'; 
import Reversal from './reversal'; 
import PaymentInfo from './paymentinfo'; 
import RiskCheck from './riskcheck'; 
import RiskCheckCheck from './riskcheckcheck'; 
import OpenInvoicePaymentInfo from './openinvoicepaymentinfo'; 
import AmexPaymentInfo from './amexpaymentinfo'; 
import BankTransferPaymentInfo from './banktransferpaymentinfo'; 
import ShopperBankAccount from './shopperbankaccount'; 
import SofortPaymentInfo from './sofortpaymentinfo'; 
import ElvPaymentInfo from './elvpaymentinfo'; 
import GiftCardPaymentInfo from './giftcardpaymentinfo'; 
import IDealPaymentInfo from './idealpaymentinfo'; 
import MaestroPaymentInfo from './maestropaymentinfo'; 
import MasterCardPaymentInfo from './mastercardpaymentinfo'; 
import MisterCashPaymentInfo from './mistercashpaymentinfo'; 
import OfflinePaymentInfo from './offlinepaymentinfo'; 
import Register from './register'; 
import PointOfSalePaymentInfo from './pointofsalepaymentinfo'; 
import PointOfSalePaymentReceipt from './pointofsalepaymentreceipt'; 
import PointOfSalePaymentReceiptValuesValue from './pointofsalepaymentreceiptvaluesvalue'; 
import SepaDirectDebitPaymentInfo from './sepadirectdebitpaymentinfo'; 
import SystemPaymentInfo from './systempaymentinfo'; 
import VisaPaymentInfo from './visapaymentinfo'; 
import ConsideredSafe from './consideredsafe'; 
import StatusErrors from './statuserrors'; 
import CaptureSuccess from './capturesuccess'; 
import CaptureErrors from './captureerrors'; 
import ProceedSuccess from './proceedsuccess'; 
import PaymentResponse from './paymentresponse'; 
import PaymentResponsePaymentSuccess from './paymentresponsepaymentsuccess'; 
import PaymentResponsePaymentError from './paymentresponsepaymenterror'; 
import ProceedErrors from './proceederrors'; 
import PaymentRedirect from './paymentredirect'; 
import ParametersParameter from './parametersparameter'; 
import StartSuccess from './startsuccess'; 
import StartErrors from './starterrors'; 
import CancelErrors from './cancelerrors'; 
import CancelSuccess from './cancelsuccess'; 
import RefundSuccess from './refundsuccess'; 
import RefundErrors from './refunderrors'; 
import IDealPaymentInput from './idealpaymentinput'; 
import ElvPaymentInput from './elvpaymentinput'; 
import OfflinePaymentInput from './offlinepaymentinput'; 
import PointOfSalePaymentInput from './pointofsalepaymentinput'; 
import BankTransferPaymentInput from './banktransferpaymentinput'; 
import DirectDebitPaymentInput from './directdebitpaymentinput'; 
import CardPaymentInput from './cardpaymentinput'; 
import ExpiryDate from './expirydate'; 
import PaymentRequestInput from './paymentrequestinput'; 
import ItemLine from './itemline'; 
import RefundItems from './refunditems'; 
import RefundItemsAdditionalRefund from './refunditemsadditionalrefund'; 
import IDealAuthorizationResult from './idealauthorizationresult'; 
import ThreeDomainSecureAuthenticationResult from './threedomainsecureauthenticationresult'; 
import CreateSuccess from './createsuccess'; 
import CreateErrors from './createerrors'; 
import SalesPerson from './salesperson'; 
import Name from './name'; 
import TechnicalIntegrationInfo from './technicalintegrationinfo'; 
import Vat from './vat'; 
import Item from './item'; 
import ItemQuantity from './itemquantity'; 
import Invoice from './invoice'; 
import InvoiceTotalVatAmount from './invoicetotalvatamount'; 
import Destination from './destination'; 
import Address from './address'; 
import PaymentReference from './paymentreference'; 
import PaymentRequest from './paymentrequest'; 
import Language from './language'; 
import Shopper from './shopper'; 
import MenuPreferences from './menupreferences'; 
import MenuPreferencesCss from './menupreferencescss'; 
import ExhortationPeriod from './exhortationperiod'; 
import PaymentPreferences from './paymentpreferences'; 
import PaymentPreferencesExhortation from './paymentpreferencesexhortation'; 
import CreateResponse from './createresponse'; 
import RefundRequest from './refundrequest'; 
import RefundResponse from './refundresponse'; 
import CancelRequest from './cancelrequest'; 
import CancelResponse from './cancelresponse'; 
import StartRequest from './startrequest'; 
import StartResponse from './startresponse'; 
import ProceedRequest from './proceedrequest'; 
import ProceedResponse from './proceedresponse'; 
import CaptureRequest from './capturerequest'; 
import CaptureResponse from './captureresponse'; 
import StatusRequest from './statusrequest'; 
import StatusResponse from './statusresponse'; 
import ExtendedStatusRequest from './extendedstatusrequest'; 
import ExtendedStatusResponse from './extendedstatusresponse'; 
import ListPaymentMethodsRequest from './listpaymentmethodsrequest'; 
import ListPaymentMethodsResponse from './listpaymentmethodsresponse'; 


var DocdataPayments = { }; 
DocdataPayments.CreateRequest = CreateRequest; 
DocdataPayments.Merchant = Merchant; 
DocdataPayments.ShopperInfo = ShopperInfo; 
DocdataPayments.CardTokenInput = CardTokenInput; 
DocdataPayments.Token = Token; 
DocdataPayments.SepaBankAccount = SepaBankAccount; 
DocdataPayments.Country = Country; 
DocdataPayments.ListPaymentMethodsSuccess = ListPaymentMethodsSuccess; 
DocdataPayments.Success = Success; 
DocdataPayments.ListPaymentMethodsErrors = ListPaymentMethodsErrors; 
DocdataPayments.Error = Error; 
DocdataPayments.StatusSuccess = StatusSuccess; 
DocdataPayments.StatusReport = StatusReport; 
DocdataPayments.ApproximateTotals = ApproximateTotals; 
DocdataPayments.Payment = Payment; 
DocdataPayments.Authorization = Authorization; 
DocdataPayments.Amount = Amount; 
DocdataPayments.Capture = Capture; 
DocdataPayments.Refund = Refund; 
DocdataPayments.Chargeback = Chargeback; 
DocdataPayments.Reversal = Reversal; 
DocdataPayments.PaymentInfo = PaymentInfo; 
DocdataPayments.RiskCheck = RiskCheck; 
DocdataPayments.RiskCheckCheck = RiskCheckCheck; 
DocdataPayments.OpenInvoicePaymentInfo = OpenInvoicePaymentInfo; 
DocdataPayments.AmexPaymentInfo = AmexPaymentInfo; 
DocdataPayments.BankTransferPaymentInfo = BankTransferPaymentInfo; 
DocdataPayments.ShopperBankAccount = ShopperBankAccount; 
DocdataPayments.SofortPaymentInfo = SofortPaymentInfo; 
DocdataPayments.ElvPaymentInfo = ElvPaymentInfo; 
DocdataPayments.GiftCardPaymentInfo = GiftCardPaymentInfo; 
DocdataPayments.IDealPaymentInfo = IDealPaymentInfo; 
DocdataPayments.MaestroPaymentInfo = MaestroPaymentInfo; 
DocdataPayments.MasterCardPaymentInfo = MasterCardPaymentInfo; 
DocdataPayments.MisterCashPaymentInfo = MisterCashPaymentInfo; 
DocdataPayments.OfflinePaymentInfo = OfflinePaymentInfo; 
DocdataPayments.Register = Register; 
DocdataPayments.PointOfSalePaymentInfo = PointOfSalePaymentInfo; 
DocdataPayments.PointOfSalePaymentReceipt = PointOfSalePaymentReceipt; 
DocdataPayments.PointOfSalePaymentReceiptValuesValue = PointOfSalePaymentReceiptValuesValue; 
DocdataPayments.SepaDirectDebitPaymentInfo = SepaDirectDebitPaymentInfo; 
DocdataPayments.SystemPaymentInfo = SystemPaymentInfo; 
DocdataPayments.VisaPaymentInfo = VisaPaymentInfo; 
DocdataPayments.ConsideredSafe = ConsideredSafe; 
DocdataPayments.StatusErrors = StatusErrors; 
DocdataPayments.CaptureSuccess = CaptureSuccess; 
DocdataPayments.CaptureErrors = CaptureErrors; 
DocdataPayments.ProceedSuccess = ProceedSuccess; 
DocdataPayments.PaymentResponse = PaymentResponse; 
DocdataPayments.PaymentResponsePaymentSuccess = PaymentResponsePaymentSuccess; 
DocdataPayments.PaymentResponsePaymentError = PaymentResponsePaymentError; 
DocdataPayments.ProceedErrors = ProceedErrors; 
DocdataPayments.PaymentRedirect = PaymentRedirect; 
DocdataPayments.ParametersParameter = ParametersParameter; 
DocdataPayments.StartSuccess = StartSuccess; 
DocdataPayments.StartErrors = StartErrors; 
DocdataPayments.CancelErrors = CancelErrors; 
DocdataPayments.CancelSuccess = CancelSuccess; 
DocdataPayments.RefundSuccess = RefundSuccess; 
DocdataPayments.RefundErrors = RefundErrors; 
DocdataPayments.IDealPaymentInput = IDealPaymentInput; 
DocdataPayments.ElvPaymentInput = ElvPaymentInput; 
DocdataPayments.OfflinePaymentInput = OfflinePaymentInput; 
DocdataPayments.PointOfSalePaymentInput = PointOfSalePaymentInput; 
DocdataPayments.BankTransferPaymentInput = BankTransferPaymentInput; 
DocdataPayments.DirectDebitPaymentInput = DirectDebitPaymentInput; 
DocdataPayments.CardPaymentInput = CardPaymentInput; 
DocdataPayments.ExpiryDate = ExpiryDate; 
DocdataPayments.PaymentRequestInput = PaymentRequestInput; 
DocdataPayments.ItemLine = ItemLine; 
DocdataPayments.RefundItems = RefundItems; 
DocdataPayments.RefundItemsAdditionalRefund = RefundItemsAdditionalRefund; 
DocdataPayments.IDealAuthorizationResult = IDealAuthorizationResult; 
DocdataPayments.ThreeDomainSecureAuthenticationResult = ThreeDomainSecureAuthenticationResult; 
DocdataPayments.CreateSuccess = CreateSuccess; 
DocdataPayments.CreateErrors = CreateErrors; 
DocdataPayments.SalesPerson = SalesPerson; 
DocdataPayments.Name = Name; 
DocdataPayments.TechnicalIntegrationInfo = TechnicalIntegrationInfo; 
DocdataPayments.Vat = Vat; 
DocdataPayments.Item = Item; 
DocdataPayments.ItemQuantity = ItemQuantity; 
DocdataPayments.Invoice = Invoice; 
DocdataPayments.InvoiceTotalVatAmount = InvoiceTotalVatAmount; 
DocdataPayments.Destination = Destination; 
DocdataPayments.Address = Address; 
DocdataPayments.PaymentReference = PaymentReference; 
DocdataPayments.PaymentRequest = PaymentRequest; 
DocdataPayments.Language = Language; 
DocdataPayments.Shopper = Shopper; 
DocdataPayments.MenuPreferences = MenuPreferences; 
DocdataPayments.MenuPreferencesCss = MenuPreferencesCss; 
DocdataPayments.ExhortationPeriod = ExhortationPeriod; 
DocdataPayments.PaymentPreferences = PaymentPreferences; 
DocdataPayments.PaymentPreferencesExhortation = PaymentPreferencesExhortation; 
DocdataPayments.CreateResponse = CreateResponse; 
DocdataPayments.RefundRequest = RefundRequest; 
DocdataPayments.RefundResponse = RefundResponse; 
DocdataPayments.CancelRequest = CancelRequest; 
DocdataPayments.CancelResponse = CancelResponse; 
DocdataPayments.StartRequest = StartRequest; 
DocdataPayments.StartResponse = StartResponse; 
DocdataPayments.ProceedRequest = ProceedRequest; 
DocdataPayments.ProceedResponse = ProceedResponse; 
DocdataPayments.CaptureRequest = CaptureRequest; 
DocdataPayments.CaptureResponse = CaptureResponse; 
DocdataPayments.StatusRequest = StatusRequest; 
DocdataPayments.StatusResponse = StatusResponse; 
DocdataPayments.ExtendedStatusRequest = ExtendedStatusRequest; 
DocdataPayments.ExtendedStatusResponse = ExtendedStatusResponse; 
DocdataPayments.ListPaymentMethodsRequest = ListPaymentMethodsRequest; 
DocdataPayments.ListPaymentMethodsResponse = ListPaymentMethodsResponse; 


export default DocdataPayments;