import CreateRequest from './createrequest';
import Merchant from './merchant'; 
import ShopperInfo from './shopperinfo'; 
import CardTokenInput from './cardtokeninput'; 
import Token from './token'; 
import SepaBankAccount from './sepabankaccount'; 
import Country from './country'; 
import ApproximateTotals from './approximatetotals';
import Payment from './payment'; 
import Authorization from './authorization'; 
import Amount from './amount'; 
import Capture from './capture'; 
import Refund from './refund'; 
import Chargeback from './chargeback'; 
import Reversal from './reversal'; 
import PaymentInfo from './paymentinfo'; 
import RiskCheck from './riskcheck'; 
import RiskCheckCheck from './riskcheckcheck'; 
import OpenInvoicePaymentInfo from './openinvoicepaymentinfo'; 
import AmexPaymentInfo from './amexpaymentinfo'; 
import BankTransferPaymentInfo from './banktransferpaymentinfo'; 
import ShopperBankAccount from './shopperbankaccount'; 
import SofortPaymentInfo from './sofortpaymentinfo'; 
import ElvPaymentInfo from './elvpaymentinfo'; 
import GiftCardPaymentInfo from './giftcardpaymentinfo'; 
import IDealPaymentInfo from './idealpaymentinfo'; 
import MaestroPaymentInfo from './maestropaymentinfo'; 
import MasterCardPaymentInfo from './mastercardpaymentinfo'; 
import MisterCashPaymentInfo from './mistercashpaymentinfo'; 
import OfflinePaymentInfo from './offlinepaymentinfo'; 
import Register from './register'; 
import PointOfSalePaymentInfo from './pointofsalepaymentinfo'; 
import PointOfSalePaymentReceipt from './pointofsalepaymentreceipt'; 
import PointOfSalePaymentReceiptValuesValue from './pointofsalepaymentreceiptvaluesvalue'; 
import SepaDirectDebitPaymentInfo from './sepadirectdebitpaymentinfo'; 
import SystemPaymentInfo from './systempaymentinfo'; 
import VisaPaymentInfo from './visapaymentinfo'; 
import ConsideredSafe from './consideredsafe'; 
import PaymentRedirect from './paymentredirect';
import ParametersParameter from './parametersparameter'; 
import IDealPaymentInput from './idealpaymentinput';
import ElvPaymentInput from './elvpaymentinput'; 
import OfflinePaymentInput from './offlinepaymentinput'; 
import PointOfSalePaymentInput from './pointofsalepaymentinput'; 
import BankTransferPaymentInput from './banktransferpaymentinput'; 
import DirectDebitPaymentInput from './directdebitpaymentinput'; 
import CardPaymentInput from './cardpaymentinput'; 
import ExpiryDate from './expirydate'; 
import PaymentRequestInput from './paymentrequestinput'; 
import ItemLine from './itemline'; 
import RefundItems from './refunditems'; 
import RefundItemsAdditionalRefund from './refunditemsadditionalrefund';
import SalesPerson from './salesperson';
import Name from './name'; 
import TechnicalIntegrationInfo from './technicalintegrationinfo'; 
import Vat from './vat'; 
import Item from './item'; 
import ItemQuantity from './itemquantity'; 
import Invoice from './invoice'; 
import InvoiceTotalVatAmount from './invoicetotalvatamount'; 
import Destination from './destination'; 
import Address from './address'; 
import PaymentReference from './paymentreference'; 
import PaymentRequest from './paymentrequest'; 
import Language from './language'; 
import Shopper from './shopper'; 
import MenuPreferences from './menupreferences'; 
import MenuPreferencesCss from './menupreferencescss'; 
import ExhortationPeriod from './exhortationperiod'; 
import PaymentPreferences from './paymentpreferences'; 
import PaymentPreferencesExhortation from './paymentpreferencesexhortation'; 
import RefundRequest from './refundrequest';
import CancelRequest from './cancelrequest';
import StartRequest from './startrequest';
import ProceedRequest from './proceedrequest';
import CaptureRequest from './capturerequest';
import StatusRequest from './statusrequest';
import ExtendedStatusRequest from './extendedstatusrequest';
import ListPaymentMethodsRequest from './listpaymentmethodsrequest';
import CancelErrors from './cancelerrors';
import CaptureErrors from './captureerrors';
import CreateErrors from './createerrors';
import ListPaymentMethodsErrors from './listpaymentmethodserrors';
import PaymentResponsePaymentError from './paymentresponsepaymenterror';
import ProceedErrors from './proceederrors';
import RefundErrors from './refunderrors';
import StartErrors from './starterrors';
import StatusErrors from './statuserrors';
import SoapClient from './soapclient';


var DocdataPayments = { };
DocdataPayments.CreateRequest = CreateRequest;
DocdataPayments.Merchant = Merchant;
DocdataPayments.ShopperInfo = ShopperInfo;
DocdataPayments.CardTokenInput = CardTokenInput;
DocdataPayments.Token = Token;
DocdataPayments.SepaBankAccount = SepaBankAccount;
DocdataPayments.Country = Country;
DocdataPayments.ApproximateTotals = ApproximateTotals;
DocdataPayments.Payment = Payment;
DocdataPayments.Authorization = Authorization;
DocdataPayments.Amount = Amount;
DocdataPayments.Capture = Capture;
DocdataPayments.Refund = Refund;
DocdataPayments.Chargeback = Chargeback;
DocdataPayments.Reversal = Reversal;
DocdataPayments.PaymentInfo = PaymentInfo;
DocdataPayments.RiskCheck = RiskCheck;
DocdataPayments.RiskCheckCheck = RiskCheckCheck;
DocdataPayments.OpenInvoicePaymentInfo = OpenInvoicePaymentInfo;
DocdataPayments.AmexPaymentInfo = AmexPaymentInfo;
DocdataPayments.BankTransferPaymentInfo = BankTransferPaymentInfo;
DocdataPayments.ShopperBankAccount = ShopperBankAccount;
DocdataPayments.SofortPaymentInfo = SofortPaymentInfo;
DocdataPayments.ElvPaymentInfo = ElvPaymentInfo;
DocdataPayments.GiftCardPaymentInfo = GiftCardPaymentInfo;
DocdataPayments.IDealPaymentInfo = IDealPaymentInfo;
DocdataPayments.MaestroPaymentInfo = MaestroPaymentInfo;
DocdataPayments.MasterCardPaymentInfo = MasterCardPaymentInfo;
DocdataPayments.MisterCashPaymentInfo = MisterCashPaymentInfo;
DocdataPayments.OfflinePaymentInfo = OfflinePaymentInfo;
DocdataPayments.Register = Register;
DocdataPayments.PointOfSalePaymentInfo = PointOfSalePaymentInfo;
DocdataPayments.PointOfSalePaymentReceipt = PointOfSalePaymentReceipt;
DocdataPayments.PointOfSalePaymentReceiptValuesValue = PointOfSalePaymentReceiptValuesValue;
DocdataPayments.SepaDirectDebitPaymentInfo = SepaDirectDebitPaymentInfo;
DocdataPayments.SystemPaymentInfo = SystemPaymentInfo;
DocdataPayments.VisaPaymentInfo = VisaPaymentInfo;
DocdataPayments.ConsideredSafe = ConsideredSafe;
DocdataPayments.PaymentRedirect = PaymentRedirect;
DocdataPayments.ParametersParameter = ParametersParameter;
DocdataPayments.IDealPaymentInput = IDealPaymentInput;
DocdataPayments.ElvPaymentInput = ElvPaymentInput;
DocdataPayments.OfflinePaymentInput = OfflinePaymentInput;
DocdataPayments.PointOfSalePaymentInput = PointOfSalePaymentInput;
DocdataPayments.BankTransferPaymentInput = BankTransferPaymentInput;
DocdataPayments.DirectDebitPaymentInput = DirectDebitPaymentInput;
DocdataPayments.CardPaymentInput = CardPaymentInput;
DocdataPayments.ExpiryDate = ExpiryDate;
DocdataPayments.PaymentRequestInput = PaymentRequestInput;
DocdataPayments.ItemLine = ItemLine;
DocdataPayments.RefundItems = RefundItems;
DocdataPayments.RefundItemsAdditionalRefund = RefundItemsAdditionalRefund;
DocdataPayments.SalesPerson = SalesPerson;
DocdataPayments.Name = Name;
DocdataPayments.TechnicalIntegrationInfo = TechnicalIntegrationInfo;
DocdataPayments.Vat = Vat;
DocdataPayments.Item = Item;
DocdataPayments.ItemQuantity = ItemQuantity;
DocdataPayments.Invoice = Invoice;
DocdataPayments.InvoiceTotalVatAmount = InvoiceTotalVatAmount;
DocdataPayments.Destination = Destination;
DocdataPayments.Address = Address;
DocdataPayments.PaymentReference = PaymentReference;
DocdataPayments.PaymentRequest = PaymentRequest;
DocdataPayments.Language = Language;
DocdataPayments.Shopper = Shopper;
DocdataPayments.MenuPreferences = MenuPreferences;
DocdataPayments.MenuPreferencesCss = MenuPreferencesCss;
DocdataPayments.ExhortationPeriod = ExhortationPeriod;
DocdataPayments.PaymentPreferences = PaymentPreferences;
DocdataPayments.PaymentPreferencesExhortation = PaymentPreferencesExhortation;
DocdataPayments.RefundRequest = RefundRequest;
DocdataPayments.CancelRequest = CancelRequest;
DocdataPayments.StartRequest = StartRequest;
DocdataPayments.ProceedRequest = ProceedRequest;
DocdataPayments.CaptureRequest = CaptureRequest;
DocdataPayments.StatusRequest = StatusRequest;
DocdataPayments.ExtendedStatusRequest = ExtendedStatusRequest;
DocdataPayments.ListPaymentMethodsRequest = ListPaymentMethodsRequest;
DocdataPayments.CancelErrors = CancelErrors;
DocdataPayments.CaptureErrors = CaptureErrors;
DocdataPayments.CreateErrors = CreateErrors;
DocdataPayments.ListPaymentMethodsErrors = ListPaymentMethodsErrors;
DocdataPayments.PaymentResponsePaymentError = PaymentResponsePaymentError;
DocdataPayments.ProceedErrors = ProceedErrors;
DocdataPayments.RefundErrors = RefundErrors;
DocdataPayments.StartErrors = StartErrors;
DocdataPayments.StatusErrors = StatusErrors;
DocdataPayments.SoapClient = SoapClient;
DocdataPayments.SoapClient = SoapClient;

module.exports = DocdataPayments;